# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Npm@1
  inputs:
    command: 'ci'
    workingDir: 'src/Web.UI'

- task: Npm@1
  inputs:
    command: 'custom'
    workingDir: 'src/Web.UI'
    customCommand: 'run release'

- task: DotNetCoreCLI@2
  inputs:
    command: 'publish'
    arguments: '--output $(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
    publishWebProjects: false
    modifyOutputPath: true
    zipAfterPublish: false